### ISSUE TITLE
Can you brief explain how to use the files in "jsonrpc" folder?

### ISSUE THREAD

**Issue by andy91129** [Mygod/bitcoin-mining#2]
As title,

I did some research and found that .py is python files, however, since I am new to python, have no idea how to use it.

BTW, I already used vivado and generated .bit file.

And I am guessing that python files is used to report hashing rate, estimated hashing rate and accepted/rejected share information.

Looking forward to your kindness reply.

Thx.

**Comment by Mygod** [comment]
You don't need to use `jsonrpc` directly. It's a dependency for `miner.py`. (and yes I don't know how to do dependency management correctly)

This project was used as my course project and was based off [teknohog's project](https://github.com/teknohog/Xilinx-Serial-Miner). To use it you just need to run `miner.py`.

**Comment by andy91129** [comment]
I encountered this error while I run **miner.py**

```
Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "C:\Users\EE-Coder\Desktop\bitcoin-mining-transform-twice\miner.py", line 14, in <module>
    from jsonrpc import proxy
  File "C:\Users\EE-Coder\Desktop\bitcoin-mining-transform-twice\jsonrpc\__init__.py", line 3, in <module>
    import six
ImportError: No module named six
>>> 
```

Any idea how to solve it?

Also, should I run **setup.py** first? ( I also encountered error while executed it.
